name: Docs Audit

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  docs-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run docs audit
        run: |
          python tools/docs_audit.py --report docs/docs_audit_report.json --check-ai-logs
      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: docs-audit-report
          path: docs/docs_audit_report.json